ts_sim: 0.01
ts_ctl: 0.01
ts_viz: 0.05

# time_factor: 1.0  # only 1x simulation is supported now

has_downwash: True
has_motor_model: True
has_battery: True

# three qd are fixed, one qd is tracking the trajectory. test the downwash effect
# enu frame
qd_init_states:
  - name: "fhnp"
    init_pos:
      - 1.0 # px
      - 1.0 # py
      - 0.5 # pz
  - name: "xiao_feng"
    init_pos:
      - 3.0 # px
      - 2.0 # py
      - 1.5 # pz
  - name: "smile_boy"
    init_pos:
      - 5.0 # px
      - 1.0 # py
      - 1.4 # pz
  - name: "wan_yue"
    init_pos:
      - 3.0 # px
      - 0.3 # py
      - 1.5 # pz
