ts_sim: 0.005
ts_ctl: 0.01
ts_viz: 0.05

# time_factor: 1.0  # only 1x simulation is supported now

has_downwash: True
has_motor_model: True
has_battery: True

# ned frame
qd_init_states:
  - name: "fhnp"
    init_pos:
      - -2.0 # px
      - 1.0 # py
      - 0.5 # pz
  - name: "xiao_feng"
    init_pos:
      - -2.0 # px
      - -1.0 # py
      - 1.5 # pz
